name: 🐛 Bug Report
description: Report a bug in Tunno
title: "[Component]: Brief description"
labels: ["bug"]
body:
  - type: dropdown
    id: app
    attributes:
      label: Application
      description: Which app is affected?
      options:
        - Desktop
        - Mobile
        - CLI
        - Web
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
      placeholder: When I do X, Y happens...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Open app
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g., 1.0.2

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, logs, or other relevant information
      placeholder: Add any other context here...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
