name: ✨ Feature Request
description: Suggest a new feature
title: "[Feature]: Brief description"
labels: ["enhancement"]
body:
  - type: dropdown
    id: app
    attributes:
      label: Application
      description: Which app would this feature be for?
      options:
        - Desktop
        - Mobile
        - CLI
        - Web
        - Multiple apps
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Other solutions you've considered

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Mockups, examples, or other information

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
