/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SongsRouteImport } from './routes/songs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FastUploadRouteImport } from './routes/fast-upload'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSyncRouteImport } from './routes/settings/sync'
import { Route as SettingsLanguageRouteImport } from './routes/settings/language'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'

const SongsRoute = SongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FastUploadRoute = FastUploadRouteImport.update({
  id: '/fast-upload',
  path: '/fast-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSyncRoute = SettingsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/fast-upload': typeof FastUploadRoute
  '/favorites': typeof FavoritesRoute
  '/playlists': typeof PlaylistsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/songs': typeof SongsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/sync': typeof SettingsSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/fast-upload': typeof FastUploadRoute
  '/favorites': typeof FavoritesRoute
  '/playlists': typeof PlaylistsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/songs': typeof SongsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/sync': typeof SettingsSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/fast-upload': typeof FastUploadRoute
  '/favorites': typeof FavoritesRoute
  '/playlists': typeof PlaylistsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/songs': typeof SongsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/sync': typeof SettingsSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artists'
    | '/fast-upload'
    | '/favorites'
    | '/playlists'
    | '/settings'
    | '/songs'
    | '/settings/appearance'
    | '/settings/language'
    | '/settings/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artists'
    | '/fast-upload'
    | '/favorites'
    | '/playlists'
    | '/settings'
    | '/songs'
    | '/settings/appearance'
    | '/settings/language'
    | '/settings/sync'
  id:
    | '__root__'
    | '/'
    | '/artists'
    | '/fast-upload'
    | '/favorites'
    | '/playlists'
    | '/settings'
    | '/songs'
    | '/settings/appearance'
    | '/settings/language'
    | '/settings/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistsRoute: typeof ArtistsRoute
  FastUploadRoute: typeof FastUploadRoute
  FavoritesRoute: typeof FavoritesRoute
  PlaylistsRoute: typeof PlaylistsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SongsRoute: typeof SongsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/songs': {
      id: '/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fast-upload': {
      id: '/fast-upload'
      path: '/fast-upload'
      fullPath: '/fast-upload'
      preLoaderRoute: typeof FastUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sync': {
      id: '/settings/sync'
      path: '/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof SettingsSyncRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/language': {
      id: '/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof SettingsLanguageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsLanguageRoute: typeof SettingsLanguageRoute
  SettingsSyncRoute: typeof SettingsSyncRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsLanguageRoute: SettingsLanguageRoute,
  SettingsSyncRoute: SettingsSyncRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistsRoute: ArtistsRoute,
  FastUploadRoute: FastUploadRoute,
  FavoritesRoute: FavoritesRoute,
  PlaylistsRoute: PlaylistsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SongsRoute: SongsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
